AspNetCore.ViewComponents.Mvc/Models/ErrorViewModel.cs
using System;

namespace AspNetCore.ViewComponents.Mvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspNetCore.ViewComponents.Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AspNetCore.ViewComponents.Mvc.Models;

namespace AspNetCore.ViewComponents.Mvc.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AspNetCore.ViewComponents.Mvc/ViewComponents/LocalViewComponent.cs
//  --------------------------------------------------------------------------------------
// AspNetCore.ViewComponents.Mvc.LocalViewComponent.cs
// 2018/02/25
//  --------------------------------------------------------------------------------------

using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCore.ViewComponents.Mvc.ViewComponents
{
    public class LocalViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(object param)
        {
            return await Task.FromResult(View(param));
        }
    }
}

AspNetCore.ViewComponents.Mvc/Views/Home/Index.cshtml
@model object

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
    <div>
        <h1>Hello from Home/Index</h1>
        <hr />
        <h1>Invoke Local Component with "A123" as arguments</h1>
        @await Component.InvokeAsync("Local", "A123")
        <hr />
        <h1>Invoke External Component with "Some Parameter" as arguments</h1>
        @await Component.InvokeAsync("External", "Some Parameter")
    </div>
</body>
</html>

AspNetCore.ViewComponents.Mvc/Views/Shared/Components/External/Default.cshtml
@model string

    <div style="background: yellow;padding: 10px">
        <h1>Hello from External Component.  You passed: @Model</h1>
    </div>

AspNetCore.ViewComponents.Mvc/Views/Shared/Components/Local/Default.cshtml
@model string
@{
    Layout = null;
}
    <div style="background: greenyellow; padding: 10px;">
        <h1>Hello from Local Component.  You passed: @Model</h1>
    </div>

AspNetCore.ViewComponents.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetCore.ViewComponents.Mvc</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AspNetCore.ViewComponents.Mvc</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - AspNetCore.ViewComponents.Mvc</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>